services:
  grafana:
    image: grafana/grafana:12.2.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - /home/meto/dev/air-quality-monitor/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /home/meto/dev/air-quality-monitor/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - /home/meto/dev/air-quality-monitor/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource@3.4.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    tmpfs:
      - /app/data
    environment:
      - RETENTION_SECONDS=86400
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
  sds011:
    build: ./air-quality-probe
    depends_on:
      - api
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - API_BASE=http://api:8000
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
  bme680:
    build: ./air-voc-probe
    depends_on: [api]
    privileged: true
    devices:
      - /dev/i2c-1:/dev/i2c-1
    environment:
      - API_BASE=http://api:8000
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
  mgs_v2:
    build: ./air-co-voc-no2-c2h5oh-probe
    depends_on: [api]
    privileged: true
    devices:
      - /dev/i2c-1:/dev/i2c-1
    environment:
      - API_BASE=http://api:8000
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
  scd4x:
    build: ./air-co2-temp-hum-probe
    depends_on: [api]
    privileged: true
    devices:
      - /dev/i2c-1:/dev/i2c-1
    environment:
      - API_BASE=http://api:8000
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
  weather-api:
    build: ./api-data-probe
    depends_on: [api]
    environment:
      - API_BASE=http://api:8000
      - WEATHER_INTERVAL_SECONDS=300
      - WEATHER_API_KEY=ae3fd22b40dd4b6295685733232603
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
volumes:
  grafana-storage: