services:
  influxdb:
    image: arm32v7/influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_LOG_ENABLED=true
      - INFLUXDB_LOGGING_LEVEL=debug
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    restart: unless-stopped

  air_co_voc_no2_c2h5oh_probe:
    build: ./air-co-voc-no2-c2h5oh-probe
    image: air-co-voc-no2-c2h5oh-probe
    container_name: air-co-voc-no2-c2h5oh-probe
    depends_on:
      - influxdb
    privileged: true
    restart: unless-stopped

  air-voc-probe:
    build: ./air-voc-probe
    image: air-voc-probe
    container_name: air-voc-probe
    depends_on:
      - influxdb
    privileged: true
    restart: unless-stopped

  air-co2-temp-hum-probe:
    build: ./air-co2-temp-hum-probe
    image: air-co2-temp-hum-probe
    container_name: air-co2-temp-hum-probe
    depends_on:
      - influxdb
    privileged: true
    restart: unless-stopped

  air-quality-probe:
    build: ./air-quality-probe
    image: air-quality-probe
    container_name: air-quality-probe
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - influxdb
    restart: unless-stopped

  api-data-probe:
    build: ./api-data-probe
    image: api-data-probe
    container_name: api-data-probe
    depends_on:
      - influxdb
    restart: unless-stopped
  
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    environment:
      INFLUXDB_URL: http://influxdb:8086
    depends_on:
      - influxdb
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
    restart: unless-stopped

  kapacitor:
    image: arm32v7/kapacitor
    container_name: kapacitor
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
      KAPACITOR_HOSTNAME: kapacitor
    volumes:
      - kapacitor_data:/var/lib/kapacitor
      - ./conf/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb-storage:
  grafana-storage:
  kapacitor_data: