version: '3'

services:
  influxdb:
    image: arm32v7/influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_LOG_ENABLED=true
      - INFLUXDB_LOGGING_LEVEL=debug
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    restart: unless-stopped

  air_quality_probe:
    image: air_quality_probe
    container_name: air_quality_probe
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - influxdb
    restart: unless-stopped
  
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    environment:
      INFLUXDB_URL: http://influxdb:8086
    depends_on:
      - influxdb
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb-storage:
  grafana-storage: