{
 "title": "Air Quality Measurement",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Real-Time Readings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PM2.5 & PM 10 Sensor Readings",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "SELECT \"PM25\", \"PM10\" FROM \"sds011\""
    }
   ]
  },
  {
   "title": "API Reference Data - PM 2.5 & PM 10",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "query": "SELECT air_quality_pm10 AS \"PM10\",  air_quality_pm2_5 AS \"PM2.5\"\n FROM weather"
    }
   ]
  },
  {
   "title": "API Reference Data - Temperature",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT temperature AS \"Temp\"\n FROM weather"
    }
   ]
  },
  {
   "title": "API Reference Data - Wind Speed",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT wind_speed AS \" Wind\"\n FROM weather"
    }
   ]
  },
  {
   "title": "Moving Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Daily Sensor Measurements Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT moving_average(\"PM25\", 360) AS \"PM 2.5\" FROM \"sds011\""
    },
    {
     "query": "SELECT moving_average(\"PM10\", 360) AS \"PM 10\" FROM \"sds011\""
    }
   ]
  }
 ]
}