{
 "title": "Air Quality Measurement",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PM2.5 & PM 10 Sensor Readings",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "SELECT \"PM25\" AS \"PM 2.5\", \"PM10\" AS \"PM 10\" FROM \"sds011\" WHERE time > now() - 24h"
    }
   ]
  },
  {
   "title": "Air Quality Score",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT \"air_quality_score\" FROM \"bme680\" WHERE time > now() - 24h"
    }
   ]
  },
  {
   "title": "Sensor Co2",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "SELECT \"CO2\" FROM \"scd4x\" WHERE time > now() - 24h"
    }
   ]
  },
  {
   "title": "Sensor NO2",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "SELECT \"NO2\" FROM \"groove_mgs_v2\" WHERE time > now() - 24h"
    }
   ]
  },
  {
   "title": "API Reference Data",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "SELECT \"temperature\" AS \"Temperature\", \"humidity\" AS \"Humidity\", \"wind_speed\" AS \"Wind-Spedd\", \"air_quality_co\" AS \"CO2\", \"air_quality_no2\" AS \"NO2\", \"air_quality_o3\" AS \"O3\", \"air_quality_so2\" AS \"SO2\", \"air_quality_pm2_5\" AS \"PM-2.5\", \"air_quality_pm10\" AS \"PM-10\" FROM \"weather\""
    }
   ]
  },
  {
   "title": "Sensor C2H5OH",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "SELECT \"C2H5OH\" FROM \"groove_mgs_v2\" WHERE time > now() - 24h"
    }
   ]
  },
  {
   "title": "Sensor CO",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "SELECT \"CO\" FROM \"groove_mgs_v2\" WHERE time > now() - 24h"
    }
   ]
  },
  {
   "title": "Sensor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "SELECT \"temp\" FROM \"bme680\" WHERE time > now() - 24h"
    }
   ]
  },
  {
   "title": "Sensor Humidity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "SELECT \"Humidity\" FROM \"scd4x\" WHERE time > now() - 24h"
    }
   ]
  }
 ]
}