{
 "title": "Air Quality Measurement",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "PM2.5 & PM 10 Sensor Readings",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"PM25\", \"PM10\" FROM \"sds011\""
    }
   ]
  },
  {
   "title": "API Reference Data",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"temperature\" AS \"Temperature\", \"humidity\" AS \"Humidity\", \"wind_speed\" AS \"Wind-Spedd\", \"air_quality_co\" AS \"CO2\", \"air_quality_no2\" AS \"NO2\", \"air_quality_o3\" AS \"O3\", \"air_quality_so2\" AS \"SO2\", \"air_quality_pm2_5\" AS \"PM-2.5\", \"air_quality_pm10\" AS \"PM-10\" FROM \"weather\""
    }
   ]
  },
  {
   "title": "Sensor Co2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "SELECT \"CO2\" FROM \"scd4x\""
    }
   ]
  },
  {
   "title": "Sensor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "SELECT \"Temperature\" FROM \"scd4x\""
    }
   ]
  },
  {
   "title": "Daily Average Sensor Measurements",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "SELECT moving_average(\"PM25\", 1440) AS \"PM 2.5\" FROM \"sds011\""
    },
    {
     "query": "SELECT moving_average(\"PM10\", 1440) AS \"PM 10\" FROM \"sds011\""
    }
   ]
  },
  {
   "title": "Sensor Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "SELECT \"Humidity\" FROM \"scd4x\""
    }
   ]
  }
 ]
}